### ISSUE TITLE
:omit-source looses Clojure files

### ISSUE THREAD

**Issue by sertel** [kumarshantanu/lein-javac-resources#1]
If you have a project that has Java and Clojure files and set `:omit-source true` then your Clojure files won't make it into the jar when doing `lein jar`.

**Comment by kumarshantanu** [comment]
Does your use-case require Clojure sources in the JAR but not the Java sources? `:omit-source true` is typically meant for AOT-compiled projects where none of the sources should end up in the JAR.

Should I just fix the README saying that the user may set `:omit-source false` to include both Java and Clojure sources in the JAR?

**Comment by sertel** [comment]
Well, fixing the README would be a first step. 

I use your plugin to deal with META-INF files in the Java-part of my project that need to be copied into the jar. So for me the best option would be to support a no-copy for Java sources as well as for Clojure source files specifically. I tried to look into your source code to find where one could add this but it seems that the `:omit-source` option is read and used by some of your dependencies.

**Comment by kumarshantanu** [comment]
Yes, `omit-source` is read and acted upon by Leiningen.
